### ISSUE TITLE
v2.0.7 Does not decrypt freshly encrypted files

### ISSUE THREAD

**Issue by Jack5005** [Picocrypt/CLI#11]
CLI version: 2.0.7
OS: Windows 11 Home

I used picocrypt's GUI exe to encrypt a directory (with paranoid enabled and most settings on). I had it encrypt each file separately thinking that it would be more secure and that when I went to decrypt it, it would be a 1-click button to decrypt the whole thing. That was not the case; please add that!

Anyhow, tried to decrypt a single file and it said:
.\picocrypt-CLI-windows-amd64.exe -k -f F:\Data\README.txt.pcv
Password: ************************
The volume header is irrecoverably damaged!

I get the same message if I try to remove the -k and -f. I don't see how the volume header could be damaged as I just encrypted the files today. 

It also removed my original files after encrypting even though I didn't want it to. So I just lost everything I encrypted. Cool.

Feedback would be greatly appreciated if there are any fixes to this! Thank you.

**Comment by Retengart** [comment]
I recreated your case. You said that you had most of the settings turned on. I assume that the "Delete Files" option was also enabled, so do not be surprised that the source files were deleted, you set this option yourself (otherwise the files COULD NOT be deleted). As for the "corrupted header", I think you have enabled the "Deniability" option, unfortunately at the moment files encrypted with it can only be decrypted in the Picocrypt GUI (I looked that the CLI code does not have the ability to work with denied volumes, @HACKERALERT I think you can comment this in more detail). 
As for file recovery, you still have your encrypted files, so you can decrypt them in the Picocrypt GUI.

**Comment by HACKERALERT** [comment]
Encrypting separately (recursive option) does not increase security.

You can decrypt multiple volumes at the same time, just put them in a folder, drop the folder, enter the password and toggle Recursive. It looks like it is encrypting but it will decrypt. This is documented in the GUI README under the Recursive feature.

If you toggled the Delete files option, of course it will delete the original files 🤦

The CLI does not support deniability at the moment and there is no way to tell that the volume is a deniable volume or random garbage (which shows the feature is doing its job, a good thing)

**Comment by Jack5005** [comment]
> I have recreated your situation on my Windows 10. You mentioned that you had most settings enabled. I assume the "Delete Files" option was enabled as well, so please don't be surprised if the source files are deleted, as you set this option yourself (otherwise, the files COULD NOT be deleted). Regarding the "corrupted header," I believe you enabled the "Deniable Encryption" option. Unfortunately, at the moment, files encrypted with this option can only be decrypted using the Picocrypt GUI. I looked into the CLI code, but it doesn't seem to have the ability to work with deniable volumes. (@HACKERALERT, I think you could comment on this more in detail). Nevertheless, regarding file recovery, your encrypted files are still available, so you can use the Picocrypt GUI to decrypt them.
@HACKERALERT I am responding to your post as well in this:
Thank you both for your replies. 

Lol, I should've been more precise just was too sleepy. I did 2 encryptions. For the one reported in this post I had enabled Paranoid mode, reed-solomon, deniability,  & recursively. I saw Delete files but intentionally **did not** select it. Mind you, I was extremely eye strained and sleepy just trying to push through so it is possible I missed it, though it would be odd as I intended to avoid it. 

I tried to use the GUI to drag the uncompressed encrypted folder into and select recursively as you instructed, which caused it to say "Unable to read comments length".

**Comment by HACKERALERT** [comment]
Yeah the Recursive mode is very prone to breaking if you don't use it as intended. Certainly not the most intuitive feature but can be useful if you figure out how it works :)
